# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RabbitGo < Formula
  desc "Android ADB command line tool"
  homepage "https://github.com/ilpanda/rabbit-go"
  version "1.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ilpanda/rabbit-go/releases/download/v1.0.6/rabbit-go_1.0.6_darwin_amd64.tar.gz"
      sha256 "d6a3b4c433f514ae5c50f762333bddc0e7a6ace9ed30ee9aab8d23ef8e0095bb"

      def install
        bin.install "rabbit-go"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ilpanda/rabbit-go/releases/download/v1.0.6/rabbit-go_1.0.6_darwin_arm64.tar.gz"
      sha256 "a87d9ce1c1c7bd49ed238c4d82892d142c78f53a56b82887641dfecce384208a"

      def install
        bin.install "rabbit-go"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ilpanda/rabbit-go/releases/download/v1.0.6/rabbit-go_1.0.6_linux_amd64.tar.gz"
      sha256 "0ef3e2f597961fc84f22c19968b5ca5d7aae4f6a1a9eaae07d2fa616ec97d3a2"
      def install
        bin.install "rabbit-go"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ilpanda/rabbit-go/releases/download/v1.0.6/rabbit-go_1.0.6_linux_arm64.tar.gz"
      sha256 "0c81c1dbcb8b105c1101c4dbb8822d363216b645cbd06117722566323f012ee8"
      def install
        bin.install "rabbit-go"
      end
    end
  end
end
