# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rabbit < Formula
  desc "Android ADB command line tool"
  homepage "https://github.com/ilpanda/rabbit-go"
  version "1.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ilpanda/rabbit-go/releases/download/v1.0.5/rabbit-go_1.0.5_darwin_amd64.tar.gz"
      sha256 "098386b588882401f50e04704d212f759f154c80b0cd4dd519973d925ecdf894"

      def install
        bin.install "rabbit-go"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ilpanda/rabbit-go/releases/download/v1.0.5/rabbit-go_1.0.5_darwin_arm64.tar.gz"
      sha256 "c34ef5fb77f1fea493a0ab271aa4964708e033d1a31e3d1e6d4709dcb14e6bd7"

      def install
        bin.install "rabbit-go"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ilpanda/rabbit-go/releases/download/v1.0.5/rabbit-go_1.0.5_linux_amd64.tar.gz"
      sha256 "7860e45ed50ca5f83a3073d1966ac0110860b403fcb799f4f6893c2221ee135f"
      def install
        bin.install "rabbit-go"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ilpanda/rabbit-go/releases/download/v1.0.5/rabbit-go_1.0.5_linux_arm64.tar.gz"
      sha256 "82a538421d83084fb5f803fa6fe5cb74f999ea4ae624f5076685d6decad906b3"
      def install
        bin.install "rabbit-go"
      end
    end
  end
end
